### ISSUE TITLE
Login page not in a responsive view

### ISSUE THREAD

**Issue by arbin0077** [AlashShrestha/GroupE_G6#9]
Login page is not in a responsive view @Dikesh9811 can you fix it ?

**Comment by Dikesh9811** [comment]
Yes, I have solved the issue of Login page UI design which is not In a Responsive view. It is solved using Bootstrap:-
![image](https://user-images.githubusercontent.com/127932182/229304718-95531446-1c60-4fa7-9b8f-23eb599bc841.png)
